### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by linjiarui6375** [Haocen2004/FuuleaHelper#1]
如题

**Comment by Haocen2004** [comment]
暂只支持任务列表查看 高考后尝试完善

**Comment by linjiarui6375** [comment]
你也高考吗
高考后咱都不用了。。。。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月25日 10:59:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Haocen2004/FuuleaHelper] 如何使用 (Issue #1)




 
暂只支持任务列表查看 高考后尝试完善

**Comment by Haocen2004** [comment]
咕咕咕（
主要是没时间摸电脑码代码
然后详情加载图片有问题 但mt任务基本是一坨图片堆起来的 特别是公式

**Comment by Haocen2004** [comment]
摸到mt2.0了 这个project不搞了
本来就是因为老版本太难用才整得这个
新版本部分设计跟本项目思路一致
